-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "macOS-White")
hl.env("XCURSOR_SIZE", "24")

-- Settings
hl.config({
    gestures = {
        workspace_swipe_touch = true,
    },
    misc = {
        vrr = 0,
    },
})
